### ISSUE TITLE
Cannot compile on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by ilia-sharafutdinov** [paynebc/tunefish#32]
Hi! I'm trying to compile tunefish4 using Linux make file. I follow the instruction and get the following while running `make` command:

`Compiling include_juce_audio_plugin_client_VST2.cpp
In file included from ../../JuceLibraryCode/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp:26,
                 from ../../JuceLibraryCode/include_juce_audio_plugin_client_VST2.cpp:9:
../../JuceLibraryCode/modules/juce_audio_plugin_client/VST/juce_VST_Wrapper.cpp:87:10: fatal error: pluginterfaces/vst2.x/aeffect.h: No such file or directory
   87 | #include "pluginterfaces/vst2.x/aeffect.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:182: build/intermediate/Debug/include_juce_audio_plugin_client_VST2_dd551e08.o] Error 1`

**Comment by opless** [comment]
Did you look at Issue #24 ?

https://github.com/paynebc/tunefish/issues/24

**Comment by ilia-sharafutdinov** [comment]
I checked it out, but didn't understand the solution.

**Comment by ilia-sharafutdinov** [comment]
So I have to install certain packages? I guess. Can you please tell which ones and if there are any additional steps?

**Comment by ShantySuffisance** [comment]
> So I have to install a certain SDK? Can you please tell which one and if there are any additional steps?

yes. you have to copy the folder `pluginterfaces` from `vstsdk2.4` to `/tunefish/src/tunefish4/JuceLibraryCode/modules ` 
you get `vstsdk2.4` from the internet archive (https://archive.org/details/VST2SDK) 
(at least that are the steps, that i belief to be relevant for my successful compilation today on Ubuntu 18.04.6 LTS x86_64)
