### ISSUE TITLE
Cannot compile on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by ShantySuffisance** [paynebc/tunefish#34]
It seams like this issue differs from #32 and #24. 

I am on Ubuntu 18.04.6 LTS x86_64 and try to get VST3 and LV2. I create the Makefile via Projucer from JUCE v7.0.1. 

The compilation stops with errors: 

`
../../Source/PluginProcessor.cpp:440:27: error: ‘showMessageBox’ is not a member of ‘juce::NativeMessageBox’
../../Source/PluginProcessor.cpp:563:21: error: ‘showMessageBox’ is not a member of ‘juce::NativeMessageBox’
` 

How can i solve this issue? Thank you all for that great synth!

**Comment by ShantySuffisance** [comment]
using JUCE v6.0.8 i was able to compile Tunefish v4.3.0
i just was stupid.
